version: '3'

services:
  frontend:
    build:
      context: ./ecom_frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./ecom_frontend:/app:cached
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./ecom_backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./ecom_backend:/app:cached
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - ./ecom_backend/.env.development
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 